-- Autogenerated by migration tool on 2022-02-03 10:14:11

-- Resource: security.jit_network_access_policies
DROP TABLE IF EXISTS azure_security_jit_network_access_policy_virtual_machines;
DROP TABLE IF EXISTS azure_security_jit_network_access_policy_requests;
DROP TABLE IF EXISTS azure_security_jit_network_access_policies;