-- Autogenerated by migration tool on 2022-02-09 15:08:48
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: network.virtual_networks
ALTER TABLE IF EXISTS "azure_network_virtual_network_subnets"
    ADD COLUMN IF NOT EXISTS "ip_configurations" jsonb;
ALTER TABLE IF EXISTS "azure_network_virtual_network_subnets"
    ADD COLUMN IF NOT EXISTS "private_endpoints" jsonb;

ALTER TABLE IF EXISTS azure_compute_virtual_machines
    ADD COLUMN "windows_configuration_patch_settings_assessment_mode" text;
ALTER TABLE IF EXISTS azure_compute_virtual_machines
    ADD COLUMN "linux_configuration_patch_settings_assessment_mode" text;
ALTER TABLE IF EXISTS azure_compute_virtual_machines
    ADD COLUMN "network_profile_network_api_version" text;
ALTER TABLE IF EXISTS azure_compute_virtual_machines
    ADD COLUMN "network_profile_network_interface_configurations" jsonb;
ALTER TABLE IF EXISTS azure_compute_virtual_machines
    ADD COLUMN "scheduled_events_profile" jsonb;
ALTER TABLE IF EXISTS azure_compute_virtual_machines
    ADD COLUMN "user_data" text;


ALTER TABLE IF EXISTS azure_compute_virtual_machine_resources
    DROP COLUMN "virtual_machine_extension_properties";
ALTER TABLE IF EXISTS azure_compute_virtual_machine_resources
    ADD COLUMN "force_update_tag" text;
ALTER TABLE IF EXISTS azure_compute_virtual_machine_resources
    ADD COLUMN "publisher" text;
ALTER TABLE IF EXISTS azure_compute_virtual_machine_resources
    ADD COLUMN "type_handler_version" text;
ALTER TABLE IF EXISTS azure_compute_virtual_machine_resources
    ADD COLUMN "auto_upgrade_minor_version" boolean;
ALTER TABLE IF EXISTS azure_compute_virtual_machine_resources
    ADD COLUMN "enable_automatic_upgrade" boolean;
ALTER TABLE IF EXISTS azure_compute_virtual_machine_resources
    ADD COLUMN "settings" jsonb;
ALTER TABLE IF EXISTS azure_compute_virtual_machine_resources
    ADD COLUMN "protected_settings" jsonb;
ALTER TABLE IF EXISTS azure_compute_virtual_machine_resources
    ADD COLUMN "provisioning_state" text;
ALTER TABLE IF EXISTS azure_compute_virtual_machine_resources
    ADD COLUMN "extension_type" text;
ALTER TABLE IF EXISTS azure_compute_virtual_machine_resources
    ADD COLUMN "instance_view" jsonb;

--it was duplicated as a json column of virtual machine
DROP TABLE IF EXISTS "azure_compute_virtual_machine_network_interfaces";

-- Resource: security.jit_network_access_policies
CREATE TABLE IF NOT EXISTS "azure_security_jit_network_access_policies"
(
    "cq_id"              uuid                        NOT NULL,
    "cq_meta"            jsonb,
    "cq_fetch_date"      timestamp without time zone NOT NULL,
    "subscription_id"    text,
    "id"                 text,
    "name"               text,
    "type"               text,
    "kind"               text,
    "location"           text,
    "provisioning_state" text,
    CONSTRAINT azure_security_jit_network_access_policies_pk PRIMARY KEY (cq_fetch_date, subscription_id, id),
    UNIQUE (cq_fetch_date, cq_id)
);
SELECT setup_tsdb_parent('azure_security_jit_network_access_policies');
CREATE TABLE IF NOT EXISTS "azure_security_jit_network_access_policy_virtual_machines"
(
    "cq_id"                           uuid                        NOT NULL,
    "cq_meta"                         jsonb,
    "cq_fetch_date"                   timestamp without time zone NOT NULL,
    "jit_network_access_policy_cq_id" uuid,
    "id"                              text,
    "ports"                           jsonb,
    "public_ip_address"               inet,
    CONSTRAINT azure_security_jit_network_access_policy_virtual_machines_pk PRIMARY KEY (cq_fetch_date, cq_id),
    UNIQUE (cq_fetch_date, cq_id)
);
CREATE INDEX ON azure_security_jit_network_access_policy_virtual_machines (cq_fetch_date, jit_network_access_policy_cq_id);
SELECT setup_tsdb_child('azure_security_jit_network_access_policy_virtual_machines', 'jit_network_access_policy_cq_id',
                        'azure_security_jit_network_access_policies', 'cq_id');
CREATE TABLE IF NOT EXISTS "azure_security_jit_network_access_policy_requests"
(
    "cq_id"                           uuid                        NOT NULL,
    "cq_meta"                         jsonb,
    "cq_fetch_date"                   timestamp without time zone NOT NULL,
    "jit_network_access_policy_cq_id" uuid,
    "virtual_machines"                text[],
    "start_time_utc"                  timestamp without time zone,
    "requestor"                       text,
    "justification"                   text,
    CONSTRAINT azure_security_jit_network_access_policy_requests_pk PRIMARY KEY (cq_fetch_date, cq_id),
    UNIQUE (cq_fetch_date, cq_id)
);
CREATE INDEX ON azure_security_jit_network_access_policy_requests (cq_fetch_date, jit_network_access_policy_cq_id);
SELECT setup_tsdb_child('azure_security_jit_network_access_policy_requests', 'jit_network_access_policy_cq_id',
                        'azure_security_jit_network_access_policies', 'cq_id');



CREATE TABLE IF NOT EXISTS "azure_resources_links"
(
    "cq_id"           uuid                        NOT NULL,
    "cq_meta"         jsonb,
    "cq_fetch_date"   timestamp without time zone NOT NULL,
    "subscription_id" text,
    "id"              text,
    "name"            text,
    "type"            text,
    "source_id"       text,
    "target_id"       text,
    "notes"           text,
    CONSTRAINT azure_resources_links_pk PRIMARY KEY (cq_fetch_date, subscription_id, id),
    UNIQUE (cq_fetch_date, cq_id)
);
SELECT setup_tsdb_parent('azure_resources_links');

CREATE TABLE IF NOT EXISTS "azure_keyvault_managed_hsm"
(
    "cq_id"                         uuid                        NOT NULL,
    "cq_meta"                       jsonb,
    "cq_fetch_date"                 timestamp without time zone NOT NULL,
    "subscription_id"               text,
    "tenant_id"                     uuid,
    "initial_admin_object_ids"      text[],
    "hsm_uri"                       text,
    "enable_soft_delete"            boolean,
    "soft_delete_retention_in_days" integer,
    "enable_purge_protection"       boolean,
    "create_mode"                   text,
    "status_message"                text,
    "provisioning_state"            text,
    "id"                            text,
    "name"                          text,
    "type"                          text,
    "location"                      text,
    "sku_family"                    text,
    "sku_name"                      text,
    "tags"                          jsonb,
    CONSTRAINT azure_keyvault_managed_hsm_pk PRIMARY KEY (cq_fetch_date, subscription_id, id),
    UNIQUE (cq_fetch_date, cq_id)
);
SELECT setup_tsdb_parent('azure_keyvault_managed_hsm');


-- Resource: compute.virtual_machine_scale_sets
CREATE TABLE IF NOT EXISTS "azure_compute_virtual_machine_scale_sets"
(
    "cq_id"                                         uuid                        NOT NULL,
    "cq_meta"                                       jsonb,
    "cq_fetch_date"                                 timestamp without time zone NOT NULL,
    "subscription_id"                               text,
    "sku_name"                                      text,
    "sku_tier"                                      text,
    "sku_capacity"                                  bigint,
    "plan_name"                                     text,
    "plan_publisher"                                text,
    "plan_product"                                  text,
    "plan_promotion_code"                           text,
    "upgrade_policy"                                jsonb,
    "automatic_repairs_policy_enabled"              boolean,
    "automatic_repairs_policy_grace_period"         text,
    "os_profile_computer_name_prefix"               text,
    "os_profile_admin_username"                     text,
    "os_profile_admin_password"                     text,
    "os_profile_custom_data"                        text,
    "os_profile_windows_configuration"              jsonb,
    "os_profile_linux_configuration"                jsonb,
    "storage_profile"                               jsonb,
    "network_profile"                               jsonb,
    "security_profile"                              jsonb,
    "diagnostics_profile"                           jsonb,
    "extension_profile_extensions_time_budget"      text,
    "license_type"                                  text,
    "priority"                                      text,
    "eviction_policy"                               text,
    "billing_profile_max_price"                     float,
    "scheduled_events_profile"                      jsonb,
    "user_data"                                     text,
    "provisioning_state"                            text,
    "overprovision"                                 boolean,
    "do_not_run_extensions_on_overprovisioned_vm_s" boolean,
    "unique_id"                                     text,
    "single_placement_group"                        boolean,
    "zone_balance"                                  boolean,
    "platform_fault_domain_count"                   integer,
    "proximity_placement_group_id"                  text,
    "host_group_id"                                 text,
    "additional_capabilities_ultra_s_s_d_enabled"   boolean,
    "scale_in_policy_rules"                         text[],
    "orchestration_mode"                            text,
    "identity_principal_id"                         text,
    "identity_tenant_id"                            text,
    "identity_type"                                 text,
    "identity_user_assigned_identities"             jsonb,
    "zones"                                         text[],
    "extended_location_name"                        text,
    "extended_location_type"                        text,
    "id"                                            text,
    "name"                                          text,
    "type"                                          text,
    "location"                                      text,
    "tags"                                          jsonb,
    CONSTRAINT azure_compute_virtual_machine_scale_sets_pk PRIMARY KEY (cq_fetch_date, subscription_id, id),
    UNIQUE (cq_fetch_date, cq_id)
);
SELECT setup_tsdb_parent('azure_compute_virtual_machine_scale_sets');
CREATE TABLE IF NOT EXISTS "azure_compute_virtual_machine_scale_set_os_profile_secrets"
(
    "cq_id"                           uuid                        NOT NULL,
    "cq_meta"                         jsonb,
    "cq_fetch_date"                   timestamp without time zone NOT NULL,
    "virtual_machine_scale_set_cq_id" uuid,
    "source_vault_id"                 text,
    "vault_certificates"              jsonb,
    CONSTRAINT azure_compute_virtual_machine_scale_set_os_profile_secrets_pk PRIMARY KEY (cq_fetch_date, cq_id),
    UNIQUE (cq_fetch_date, cq_id)
);
CREATE INDEX ON azure_compute_virtual_machine_scale_set_os_profile_secrets (cq_fetch_date, virtual_machine_scale_set_cq_id);
SELECT setup_tsdb_child('azure_compute_virtual_machine_scale_set_os_profile_secrets', 'virtual_machine_scale_set_cq_id',
                        'azure_compute_virtual_machine_scale_sets', 'cq_id');
CREATE TABLE IF NOT EXISTS "azure_compute_virtual_machine_scale_set_extensions"
(
    "cq_id"                           uuid                        NOT NULL,
    "cq_meta"                         jsonb,
    "cq_fetch_date"                   timestamp without time zone NOT NULL,
    "virtual_machine_scale_set_cq_id" uuid,
    "type"                            text,
    "extension_type"                  text,
    "name"                            text,
    "force_update_tag"                text,
    "publisher"                       text,
    "type_handler_version"            text,
    "auto_upgrade_minor_version"      boolean,
    "enable_automatic_upgrade"        boolean,
    "settings"                        jsonb,
    "protected_settings"              jsonb,
    "provisioning_state"              text,
    "provision_after_extensions"      text[],
    "id"                              text,
    CONSTRAINT azure_compute_virtual_machine_scale_set_extensions_pk PRIMARY KEY (cq_fetch_date, cq_id),
    UNIQUE (cq_fetch_date, cq_id)
);
CREATE INDEX ON azure_compute_virtual_machine_scale_set_extensions (cq_fetch_date, virtual_machine_scale_set_cq_id);
SELECT setup_tsdb_child('azure_compute_virtual_machine_scale_set_extensions', 'virtual_machine_scale_set_cq_id',
                        'azure_compute_virtual_machine_scale_sets', 'cq_id');
