-- Autogenerated by migration tool on 2022-02-21 18:25:58
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: batch.accounts
DROP TABLE IF EXISTS azure_batch_account_private_endpoint_connections;
DROP TABLE IF EXISTS azure_batch_accounts;
