-- Autogenerated by migration tool on 2022-02-17 08:48:12
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: search.services
DROP TABLE IF EXISTS azure_search_service_private_endpoint_connections;
DROP TABLE IF EXISTS azure_search_service_shared_private_link_resources;
DROP TABLE IF EXISTS azure_search_services;
