-- Autogenerated by migration tool on 2022-02-02 17:58:38
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: network.public_ip_addresses
ALTER TABLE IF EXISTS "azure_network_public_ip_addresses" ADD COLUMN IF NOT EXISTS "extended_location_name." text; -- could this be "extended_location_type" ?
-- ALTER TABLE "azure_network_public_ip_addresses" RENAME COLUMN "extended_location_type" TO "extended_location_name."; -- uncomment to activate, remove ADD/DROP COLUMN above and below
ALTER TABLE IF EXISTS "azure_network_public_ip_addresses" ADD COLUMN IF NOT EXISTS "extended_location_type." text; -- could this be "extended_location_type" ?
-- ALTER TABLE "azure_network_public_ip_addresses" RENAME COLUMN "extended_location_type" TO "extended_location_type."; -- uncomment to activate, remove ADD/DROP COLUMN above and below
ALTER TABLE IF EXISTS "azure_network_public_ip_addresses" DROP COLUMN IF EXISTS "extended_location_name"; -- could this be "extended_location_type." ? Check the RENAME COLUMN statement above
ALTER TABLE IF EXISTS "azure_network_public_ip_addresses" DROP COLUMN IF EXISTS "extended_location_type"; -- could this be "extended_location_type." ? Check the RENAME COLUMN statement above

-- Resource: sql.servers
CREATE TABLE IF NOT EXISTS "azure_sql_server_virtual_network_rules" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"cq_fetch_date" timestamp without time zone NOT NULL,
	"server_cq_id" uuid,
	"id" text,
	"name" text,
	"type" text,
	"subnet_id" text,
	"ignore_missing_vnet_service_endpoint" boolean,
	"state" text,
	CONSTRAINT azure_sql_server_virtual_network_rules_pk PRIMARY KEY(cq_fetch_date,server_cq_id,id),
	UNIQUE(cq_fetch_date,cq_id)
);
CREATE INDEX ON azure_sql_server_virtual_network_rules (cq_fetch_date, server_cq_id);
SELECT setup_tsdb_child('azure_sql_server_virtual_network_rules', 'server_cq_id', 'azure_sql_servers', 'cq_id');
