-- Autogenerated by migration tool on 2022-03-07 15:52:25
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: eventhub.namespaces
ALTER TABLE IF EXISTS "azure_eventhub_namespaces" DROP COLUMN IF EXISTS "network_rule_set";

-- Resource: search.services
DROP TABLE IF EXISTS azure_search_service_private_endpoint_connections;
DROP TABLE IF EXISTS azure_search_service_shared_private_link_resources;
DROP TABLE IF EXISTS azure_search_services;

-- Resource: sql.servers
ALTER TABLE IF EXISTS "azure_sql_databases" DROP COLUMN IF EXISTS "backup_long_term_retention_policy";
