-- Autogenerated by migration tool on 2022-02-07 17:41:37
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: cosmosdb.accounts
DROP TABLE IF EXISTS azure_cosmosdb_account_capabilities;
DROP TABLE IF EXISTS azure_cosmosdb_account_write_locations;
DROP TABLE IF EXISTS azure_cosmosdb_account_read_locations;
DROP TABLE IF EXISTS azure_cosmosdb_account_locations;
DROP TABLE IF EXISTS azure_cosmosdb_account_failover_policies;
DROP TABLE IF EXISTS azure_cosmosdb_account_private_endpoint_connections;
DROP TABLE IF EXISTS azure_cosmosdb_account_cors;
DROP TABLE IF EXISTS azure_cosmosdb_accounts;

-- Resource: cosmosdb.mongodb_databases
DROP TABLE IF EXISTS azure_cosmosdb_mongodb_databases;

-- Resource: cosmosdb.sql_databases
DROP TABLE IF EXISTS azure_cosmosdb_sql_databases;
