-- Autogenerated by migration tool on 2022-02-16 10:52:47
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: mariadb.servers
DROP TABLE IF EXISTS azure_mariadb_server_private_endpoint_connections;
DROP TABLE IF EXISTS azure_mariadb_server_configurations;
DROP TABLE IF EXISTS azure_mariadb_servers;
