-- Resource: compute.virtual_machine_scale_sets
DROP TABLE IF EXISTS azure_compute_virtual_machine_scale_set_os_profile_secrets;
DROP TABLE IF EXISTS azure_compute_virtual_machine_scale_set_extensions;
DROP TABLE IF EXISTS azure_compute_virtual_machine_scale_sets;
