-- Autogenerated by migration tool on 2022-02-17 08:48:20
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: search.services
CREATE TABLE IF NOT EXISTS "azure_search_services" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"subscription_id" text,
	"replica_count" integer,
	"partition_count" integer,
	"hosting_mode" text,
	"public_network_access" text,
	"status" text,
	"status_details" text,
	"provisioning_state" text,
	"network_rule_set_ip_rules" text[],
	"sku_name" text,
	"identity_principal_id" text,
	"identity_tenant_id" text,
	"identity_type" text,
	"tags" jsonb,
	"location" text,
	"id" text,
	"name" text,
	"type" text,
	CONSTRAINT azure_search_services_pk PRIMARY KEY(subscription_id,id),
	UNIQUE(cq_id)
);
CREATE TABLE IF NOT EXISTS "azure_search_service_private_endpoint_connections" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"service_cq_id" uuid,
	"private_endpoint_id" text,
	"private_link_service_connection_state_status" text,
	"private_link_service_connection_state_description" text,
	"private_link_service_connection_state_actions_required" text,
	"id" text,
	"name" text,
	"type" text,
	CONSTRAINT azure_search_service_private_endpoint_connections_pk PRIMARY KEY(cq_id),
	UNIQUE(cq_id),
	FOREIGN KEY (service_cq_id) REFERENCES azure_search_services(cq_id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "azure_search_service_shared_private_link_resources" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"service_cq_id" uuid,
	"private_link_resource_id" text,
	"group_id" text,
	"request_message" text,
	"resource_region" text,
	"status" text,
	"provisioning_state" text,
	"id" text,
	"name" text,
	"type" text,
	CONSTRAINT azure_search_service_shared_private_link_resources_pk PRIMARY KEY(cq_id),
	UNIQUE(cq_id),
	FOREIGN KEY (service_cq_id) REFERENCES azure_search_services(cq_id) ON DELETE CASCADE
);
