-- Autogenerated by migration tool on 2022-02-02 18:04:15
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: sql.servers
DROP TABLE IF EXISTS azure_sql_server_virtual_network_rules;

-- Resource: redis.services
DROP TABLE IF EXISTS azure_redis_services;

-- Resource: sql.managed_instances
DROP TABLE IF EXISTS azure_sql_managed_database_vulnerability_assessments;
DROP TABLE IF EXISTS azure_sql_managed_database_vulnerability_assessment_scans;
DROP TABLE IF EXISTS azure_sql_managed_databases;
DROP TABLE IF EXISTS azure_sql_managed_instance_private_endpoint_connections;
DROP TABLE IF EXISTS azure_sql_managed_instance_vulnerability_assessments;
DROP TABLE IF EXISTS azure_sql_managed_instance_encryption_protectors;
DROP TABLE IF EXISTS azure_sql_managed_instances;
