-- Autogenerated by migration tool on 2022-02-02 17:56:36
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: network.public_ip_addresses
ALTER TABLE IF EXISTS "azure_network_public_ip_addresses" DROP COLUMN IF EXISTS "extended_location_name."; -- could this be "extended_location_type" ?
-- ALTER TABLE "azure_network_public_ip_addresses" RENAME COLUMN "extended_location_name." TO "extended_location_type"; -- uncomment to activate, remove ADD/DROP COLUMN above and below
ALTER TABLE IF EXISTS "azure_network_public_ip_addresses" DROP COLUMN IF EXISTS "extended_location_type."; -- could this be "extended_location_type" ?
-- ALTER TABLE "azure_network_public_ip_addresses" RENAME COLUMN "extended_location_type." TO "extended_location_type"; -- uncomment to activate, remove ADD/DROP COLUMN above and below
ALTER TABLE IF EXISTS "azure_network_public_ip_addresses" ADD COLUMN IF NOT EXISTS "extended_location_name" text; -- could this be "extended_location_type." ? Check the RENAME COLUMN statement above
ALTER TABLE IF EXISTS "azure_network_public_ip_addresses" ADD COLUMN IF NOT EXISTS "extended_location_type" text; -- could this be "extended_location_type." ? Check the RENAME COLUMN statement above

-- Resource: sql.servers
DROP TABLE IF EXISTS azure_sql_server_virtual_network_rules;
