// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudquery/cq-provider-azure/client/services (interfaces: ADApplicationsClient,ADGroupsClient,ADServicePrinicpals,ADUsersClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	graphrbac "github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac"
	gomock "github.com/golang/mock/gomock"
)

// MockADApplicationsClient is a mock of ADApplicationsClient interface.
type MockADApplicationsClient struct {
	ctrl     *gomock.Controller
	recorder *MockADApplicationsClientMockRecorder
}

// MockADApplicationsClientMockRecorder is the mock recorder for MockADApplicationsClient.
type MockADApplicationsClientMockRecorder struct {
	mock *MockADApplicationsClient
}

// NewMockADApplicationsClient creates a new mock instance.
func NewMockADApplicationsClient(ctrl *gomock.Controller) *MockADApplicationsClient {
	mock := &MockADApplicationsClient{ctrl: ctrl}
	mock.recorder = &MockADApplicationsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockADApplicationsClient) EXPECT() *MockADApplicationsClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockADApplicationsClient) List(arg0 context.Context, arg1 string) (graphrbac.ApplicationListResultPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(graphrbac.ApplicationListResultPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockADApplicationsClientMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockADApplicationsClient)(nil).List), arg0, arg1)
}

// MockADGroupsClient is a mock of ADGroupsClient interface.
type MockADGroupsClient struct {
	ctrl     *gomock.Controller
	recorder *MockADGroupsClientMockRecorder
}

// MockADGroupsClientMockRecorder is the mock recorder for MockADGroupsClient.
type MockADGroupsClientMockRecorder struct {
	mock *MockADGroupsClient
}

// NewMockADGroupsClient creates a new mock instance.
func NewMockADGroupsClient(ctrl *gomock.Controller) *MockADGroupsClient {
	mock := &MockADGroupsClient{ctrl: ctrl}
	mock.recorder = &MockADGroupsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockADGroupsClient) EXPECT() *MockADGroupsClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockADGroupsClient) List(arg0 context.Context, arg1 string) (graphrbac.GroupListResultPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(graphrbac.GroupListResultPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockADGroupsClientMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockADGroupsClient)(nil).List), arg0, arg1)
}

// MockADServicePrinicpals is a mock of ADServicePrinicpals interface.
type MockADServicePrinicpals struct {
	ctrl     *gomock.Controller
	recorder *MockADServicePrinicpalsMockRecorder
}

// MockADServicePrinicpalsMockRecorder is the mock recorder for MockADServicePrinicpals.
type MockADServicePrinicpalsMockRecorder struct {
	mock *MockADServicePrinicpals
}

// NewMockADServicePrinicpals creates a new mock instance.
func NewMockADServicePrinicpals(ctrl *gomock.Controller) *MockADServicePrinicpals {
	mock := &MockADServicePrinicpals{ctrl: ctrl}
	mock.recorder = &MockADServicePrinicpalsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockADServicePrinicpals) EXPECT() *MockADServicePrinicpalsMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockADServicePrinicpals) List(arg0 context.Context, arg1 string) (graphrbac.ServicePrincipalListResultPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(graphrbac.ServicePrincipalListResultPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockADServicePrinicpalsMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockADServicePrinicpals)(nil).List), arg0, arg1)
}

// MockADUsersClient is a mock of ADUsersClient interface.
type MockADUsersClient struct {
	ctrl     *gomock.Controller
	recorder *MockADUsersClientMockRecorder
}

// MockADUsersClientMockRecorder is the mock recorder for MockADUsersClient.
type MockADUsersClientMockRecorder struct {
	mock *MockADUsersClient
}

// NewMockADUsersClient creates a new mock instance.
func NewMockADUsersClient(ctrl *gomock.Controller) *MockADUsersClient {
	mock := &MockADUsersClient{ctrl: ctrl}
	mock.recorder = &MockADUsersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockADUsersClient) EXPECT() *MockADUsersClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockADUsersClient) List(arg0 context.Context, arg1, arg2 string) (graphrbac.UserListResultPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].(graphrbac.UserListResultPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockADUsersClientMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockADUsersClient)(nil).List), arg0, arg1, arg2)
}
