// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudquery/cq-provider-azure/client/services (interfaces: SecuritySettingsClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	security "github.com/Azure/azure-sdk-for-go/services/preview/security/mgmt/v3.0/security"
	gomock "github.com/golang/mock/gomock"
)

// MockSecuritySettingsClient is a mock of SecuritySettingsClient interface.
type MockSecuritySettingsClient struct {
	ctrl     *gomock.Controller
	recorder *MockSecuritySettingsClientMockRecorder
}

// MockSecuritySettingsClientMockRecorder is the mock recorder for MockSecuritySettingsClient.
type MockSecuritySettingsClientMockRecorder struct {
	mock *MockSecuritySettingsClient
}

// NewMockSecuritySettingsClient creates a new mock instance.
func NewMockSecuritySettingsClient(ctrl *gomock.Controller) *MockSecuritySettingsClient {
	mock := &MockSecuritySettingsClient{ctrl: ctrl}
	mock.recorder = &MockSecuritySettingsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecuritySettingsClient) EXPECT() *MockSecuritySettingsClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSecuritySettingsClient) List(arg0 context.Context) (security.SettingsListPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].(security.SettingsListPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSecuritySettingsClientMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSecuritySettingsClient)(nil).List), arg0)
}
