// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudquery/cq-provider-azure/client/services (interfaces: SecurityAutoProvisioningSettingsClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	security "github.com/Azure/azure-sdk-for-go/services/preview/security/mgmt/v3.0/security"
	gomock "github.com/golang/mock/gomock"
)

// MockSecurityAutoProvisioningSettingsClient is a mock of SecurityAutoProvisioningSettingsClient interface.
type MockSecurityAutoProvisioningSettingsClient struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityAutoProvisioningSettingsClientMockRecorder
}

// MockSecurityAutoProvisioningSettingsClientMockRecorder is the mock recorder for MockSecurityAutoProvisioningSettingsClient.
type MockSecurityAutoProvisioningSettingsClientMockRecorder struct {
	mock *MockSecurityAutoProvisioningSettingsClient
}

// NewMockSecurityAutoProvisioningSettingsClient creates a new mock instance.
func NewMockSecurityAutoProvisioningSettingsClient(ctrl *gomock.Controller) *MockSecurityAutoProvisioningSettingsClient {
	mock := &MockSecurityAutoProvisioningSettingsClient{ctrl: ctrl}
	mock.recorder = &MockSecurityAutoProvisioningSettingsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityAutoProvisioningSettingsClient) EXPECT() *MockSecurityAutoProvisioningSettingsClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSecurityAutoProvisioningSettingsClient) List(arg0 context.Context) (security.AutoProvisioningSettingListPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].(security.AutoProvisioningSettingListPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSecurityAutoProvisioningSettingsClientMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSecurityAutoProvisioningSettingsClient)(nil).List), arg0)
}
