// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudquery/cq-provider-azure/client/services (interfaces: SubscriptionsClient,TenantsClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	runtime "github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	armsubscriptions "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armsubscriptions"
	subscription "github.com/Azure/azure-sdk-for-go/services/subscription/mgmt/2020-09-01/subscription"
	gomock "github.com/golang/mock/gomock"
)

// MockSubscriptionsClient is a mock of SubscriptionsClient interface.
type MockSubscriptionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionsClientMockRecorder
}

// MockSubscriptionsClientMockRecorder is the mock recorder for MockSubscriptionsClient.
type MockSubscriptionsClientMockRecorder struct {
	mock *MockSubscriptionsClient
}

// NewMockSubscriptionsClient creates a new mock instance.
func NewMockSubscriptionsClient(ctrl *gomock.Controller) *MockSubscriptionsClient {
	mock := &MockSubscriptionsClient{ctrl: ctrl}
	mock.recorder = &MockSubscriptionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionsClient) EXPECT() *MockSubscriptionsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSubscriptionsClient) Get(arg0 context.Context, arg1 string) (subscription.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(subscription.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSubscriptionsClientMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSubscriptionsClient)(nil).Get), arg0, arg1)
}

// ListLocations mocks base method.
func (m *MockSubscriptionsClient) ListLocations(arg0 context.Context, arg1 string) (subscription.LocationListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLocations", arg0, arg1)
	ret0, _ := ret[0].(subscription.LocationListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLocations indicates an expected call of ListLocations.
func (mr *MockSubscriptionsClientMockRecorder) ListLocations(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLocations", reflect.TypeOf((*MockSubscriptionsClient)(nil).ListLocations), arg0, arg1)
}

// MockTenantsClient is a mock of TenantsClient interface.
type MockTenantsClient struct {
	ctrl     *gomock.Controller
	recorder *MockTenantsClientMockRecorder
}

// MockTenantsClientMockRecorder is the mock recorder for MockTenantsClient.
type MockTenantsClientMockRecorder struct {
	mock *MockTenantsClient
}

// NewMockTenantsClient creates a new mock instance.
func NewMockTenantsClient(ctrl *gomock.Controller) *MockTenantsClient {
	mock := &MockTenantsClient{ctrl: ctrl}
	mock.recorder = &MockTenantsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantsClient) EXPECT() *MockTenantsClientMockRecorder {
	return m.recorder
}

// NewListPager mocks base method.
func (m *MockTenantsClient) NewListPager(arg0 *armsubscriptions.TenantsClientListOptions) *runtime.Pager[armsubscriptions.TenantsClientListResponse] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListPager", arg0)
	ret0, _ := ret[0].(*runtime.Pager[armsubscriptions.TenantsClientListResponse])
	return ret0
}

// NewListPager indicates an expected call of NewListPager.
func (mr *MockTenantsClientMockRecorder) NewListPager(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListPager", reflect.TypeOf((*MockTenantsClient)(nil).NewListPager), arg0)
}
