name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37.1

  docs:
    name: docs verification
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - uses: actions/checkout@v2
      - name: build-docs
        run: |
          ls -la
          go run ./docs/docs.go
      - uses: technote-space/get-diff-action@v4
        id: git-diff
        with:
          PATTERNS: |
            +(docs)/tables/*.md
      - name: fail-step
        run: exit 1
        if: steps.git-diff.outputs.diff