# DONT EDIT. This file is synced from https://github.com/cloudquery/.github/.github
name: terraform_plan
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terrafrom_plan:
    env:
      ARM_USE_MSI: true
    permissions:
        id-token: write
        contents: read    # This is required for actions/checkout@v2
    name: Terrafrom Plan
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # In this scenario we are not using OIDC yet because we are waiting for
      # https://github.com/hashicorp/go-azure-helpers/issues/91
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: ./scripts/terraform-fmt-change-only.sh
        continue-on-error: true

      - name: Terraform Validate
        id: validate
        run: ./scripts/terraform-validate-change-only.sh

      - name: Terraform Plan
        id: plan
        run: ./scripts/terraform-plan-change-only.sh

