# DONT EDIT. This file is synced from https://github.com/cloudquery/.github/.github
name: terraform_apply
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terrafrom_apply:
    # In this scenario we are not using OIDC yet because we are waiting for
    # https://github.com/hashicorp/go-azure-helpers/issues/91
    env:
      ARM_CLIENT_ID: $
      ARM_CLIENT_SECRET: $
      ARM_SUBSCRIPTION_ID: $
      ARM_TENANT_ID: $
    permissions:
        id-token: write
        contents: read    # This is required for actions/checkout@v2
    name: Terrafrom Apply
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Apply
        id: apply
        run: ./scripts/terraform-apply-changes-only.sh
